version: '3.8'

services:
  app:
    build:
      target: ${TARGET:-dev}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  tests:
    build:
      target: ${TARGET:-test}
    depends_on:
      - app
